### ISSUE TITLE
Attribute vectors for arbitrary images?

### ISSUE THREAD

**Issue by power0341** [xcyan/eccv16_attr2img#1]
Hi, I wonder how to get the corresponding attribute vector of a given image (one not in the valData) for testing, so I can just change one attribute while keep others intact.

**Comment by xcyan** [comment]
Please refer to this file:
http://www.cs.columbia.edu/CAVE/databases/pubfig/download/lfw_attributes.txt

The attribute order (73-dim vector) should be the same.
