### ISSUE TITLE
How to convert training networks so they do not require CUDA?

### ISSUE THREAD

**Issue by mlerma54** [xcyan/eccv16_attr2img#4]
I was finally able to train the networks using leased time in a GPU cluster, saved the trained networks (the net-epoch-100.t7 files), and run the decoder for testing. Everything runs fine in the GPU cluster, but when trying to use the trained networks on a machine _without_ GPU the net-epoch-100.t7 files cannot be loaded. Speed is indeed needed for training, but, after the network has been trained, just feeding attributes + latent variables to the decoder to get synthetic images is a different matter. Is there any way to convert the net-epoch-100.t7 files into something equivalent that does not require using a GPU? Thank you!

**Comment by xcyan** [comment]
@mlerma54 https://groups.google.com/forum/#!topic/torch7/ugBCwaoXw_s

**Comment by mlerma54** [comment]
Thank you.

**Comment by xcyan** [comment]
@mlerma54 Just in case you run into this issue:

> The generated images are rather noisy to say the least.

Please add the following two lines when you evaluating the model from previous checkpoints:
`encoder:evaluate()`
`decoder:evaluate()`
Basically, it removes the dropout layer that introduces noise used during training.

**Comment by mlerma54** [comment]
Yes, I noticed, thank you!
